### ISSUE TITLE
libmypaint submodule stuck on old version, gimp-git build needs newer libmypaint

### ISSUE THREAD

**Issue by ShadowKyogre** [mypaint/mypaint#683]
Related to #535

#### Description of the problem
Upstream gimp-git is doing a version check for libmypaint 1.3.0. However, it's impossible to do this with the current state of mypaint master.

See this link for more information: <https://git.gnome.org/browse/gimp/tree/configure.ac#n70>

Master has this: "brushlib @ 65ffae1"

At that commit, this is the version reported: <https://github.com/mypaint/libmypaint/blob/65ffae19bc152749d30e78593b7f78749b294718/SConscript#L6>

But in master for libmypaint, it reports 1.3.0: <https://github.com/mypaint/libmypaint/blob/master/configure.ac#L5-L7>

What would be the recommended course of action for this discrepancy?

#### Basic system details

MyPaint version: git revision g1fc6f4c
Operating system: Arch Linux
Desktop environment: N/A (Using Compiz as a standalone window manager)

#### Steps to reproduce

1. Clone mypaint
2. Update the submodule as mentioned in the instructions
3. It should be at the mentioned revision
4. run 'git submodule update --remote --merge'
5. mypaint should fail to build when you try to run scons

#### Backtraces or error messages

I haven't tried to rebuild gimp today. I was notified of this via aaronp on the AUR. See https://aur.archlinux.org/packages/mypaint-git/#news for aaronp's comment

However, I did get this error message:
~~~~
scons: Reading SConscript files ...
building for 'python2.7' (use scons python_binary=xxx to change)
using 'python2.7-config' (use scons python_config=xxx to change)
Delete(["libmypaint-tests.so", "libmypaint-tests.so", "libmypaint.so", "libmypaintlib.so", "libmypaint.a", "libmypaint-tests.a", "lib/_mypaintlib.so"])
Enabling i18n for brushlib in full application build

scons: warning: Ignoring missing SConscript 'brushlib/SConscript'
File "/home/shadowkyogre/code/aur-pbds/mypaint-git/src/mypaint/SConstruct", line 235, in <module>

----------------------------------------------------------------------

Missing submodule "brushlib"

Please run "git submodule update --init" to create it. See the README
for more information.

----------------------------------------------------------------------
~~~~

When I tried working around it by creating an empty brushlib/SConscript file:
~~~~
scons: Reading SConscript files ...
building for 'python2.7' (use scons python_binary=xxx to change)
using 'python2.7-config' (use scons python_config=xxx to change)
Delete(["libmypaint-tests.so", "libmypaint-tests.so", "libmypaint.so", "libmypaintlib.so", "libmypaint.a", "libmypaint-tests.a", "lib/_mypaintlib.so"])
Enabling i18n for brushlib in full application build
set umask to 0022 (was 0022)
scons: done reading SConscript files.
scons: Building targets ...
swig -o lib/mypaintlib_wrap.cc -Wall -noproxydel -python -c++ -DNO_TESTS lib/mypaintlib.i
g++ -o lib/mypaintlib_wrap.os -c -march=native -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -march=native -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -g -pthread -DNO_TESTS -fPIC -DHAVE_GTK3 -Ibrushlib -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/pygobject-3.0 -I/usr/lib/libffi-3.2.1/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 lib/mypaintlib_wrap.cc
In file included from lib/mypaintlib.hpp:13:0,
                 from lib/mypaintlib_wrap.cc:3143:
lib/mapping.hpp:20:21: fatal error: mapping.h: No such file or directory
 #include "mapping.h"
                     ^
compilation terminated.
scons: *** [lib/mypaintlib_wrap.os] Error 1
scons: building terminated because of errors.
~~~~

**Comment by achadwick** [comment]
Not a problem with MyPaint; we do not maintain gimp-git. You should not be trying to do this with MyPpaint master.

Follow the instructions and install https://github.com/mypaint/libmypaint

Or try https://github.com/mypaint/libmypaint.deb on a Debian system.

**Comment by ShadowKyogre** [comment]
@achadwick : Yes, I'm not aware that you maintain gimp-git.

However, this is completely relevant **to** mypaint because I'm using both mypaint master and gimp-git. I'm the AUR maintainer for the mypaint-git PKGBUILD for those who want to try out mypaint straight from the git repo.

The main reason I'm concerned about building gimp with libmypaint is because I use gimp-git for reporting back any issues I find in gimp so they can get fixed before the next major release.

Please reconsider your stance on this issue.

**Comment by achadwick** [comment]
> Please reconsider your stance on this issue.

Very well. I guess I can take this as a request to merge the MyPaint build changes sooner. I was hoping to release libmypaint tonight though.

Libmypaint now builds independently, so do that please if you are tracking both programs out of git and need to get stuff done now.

MyPaint master will be dropping the submodule _probably_ tonight, and you will need to create an independent libmypaint-git PKGBUILD. In other words, it soon will be **impossible to build libmypaint by building MyPaint**. Here's an example I did for MSYS2: <https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libmypaint-git>. I'd appreciate a sanity check over the pkgver and conflicts stuff, as a Debian guy. Feel free to steal my stanzas or report glaring errors against my fork of MINGW-packages.

**Comment by ShadowKyogre** [comment]
@achadwick : Understood. The libmypaint-git PKGBUILD is already up and maintained by someone else. What I'll need to do on my end is modify the mypaint-git PKGBUILD to properly reflect the dependency against libmypaint-git since they should no longer conflict.

That being said, I'll go check out the PKGBUILD you linked up there! I'll let you know if I encounter any glaring errors.

Thanks a bunch for this.

**Comment by ShadowKyogre** [comment]
I'll need to notify the libmypaint-git maintainer about the modified PKGBUILD I'll provide them to build using autoconf. Not sure how that slipped out of my mind.
